name: pathogen_ml
channels:
  - conda-forge
  - bioconda
dependencies:
  - python>=3.10
  - pandas
  - numpy
  - scikit-learn
  - xgboost
  - biopython
  - requests
  - tqdm
  - ppanggolin
  - blast
  - jupyterlab
